site_name: MkLorum
nav:
  - Home: index.md
  - About: about.md
  - DocStrings: docstr.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false