site_name: MkLorum
nav:
  - Home: index.md
  - About: about.md
  - DocStrings: docstr.md

theme:
  name: mkdocs

plugins:
  - search
  - autorefs
  - include
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false